DROP DATABASE IF EXISTS my;
CREATE DATABASE my;
USE my;
DROP TABLE IF EXISTS myxtable;
CREATE TABLE myxtable (`Serial Number` varchar(255),`Company Name` varchar(255),`Employee Markme` varchar(255),`Description` varchar(255),`Leave` varchar(255));
INSERT INTO myxtable(`Serial Number`,`Company Name`,`Employee Markme`,`Description`,`Leave`) VALUES ("9788189999599","TALES OF SHIVA","Mark","mark","0");
INSERT INTO myxtable(`Serial Number`,`Company Name`,`Employee Markme`,`Description`,`Leave`) VALUES ("9780099578079","1Q84 THE COMPLETE TRILOGY","HARUKI MURAKAMI","Mark","0");
INSERT INTO myxtable(`Serial Number`,`Company Name`,`Employee Markme`,`Description`,`Leave`) VALUES ("9780198082897","MY KUMAN","Mark","Mark","0");
INSERT INTO myxtable(`Serial Number`,`Company Name`,`Employee Markme`,`Description`,`Leave`) VALUES ("9780007880331","THE GOD OF SMAAL THINGS","ARUNDHATI ROY","4TH HARPER COLLINS","2");
INSERT INTO myxtable(`Serial Number`,`Company Name`,`Employee Markme`,`Description`,`Leave`) VALUES ("9780545060455","THE BLACK CIRCLE","Mark","4TH HARPER COLLINS","0");
INSERT INTO myxtable(`Serial Number`,`Company Name`,`Employee Markme`,`Description`,`Leave`) VALUES ("9788126525072","THE THREE LAWS OF PERFORMANCE","Mark","4TH HARPER COLLINS","0");
